version: '3.8'

services:
  app:
    build:
      context: InnoMusicRoomBot
      dockerfile: Dockerfile
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./usersettings.json:/app/usersettings.json
      - ./musroom.db:/app/musroom.db
    restart: always